"a{ color: black; }\n"
    "body {\n"
    "font-size: 16px;\n"
    "width: 90%;\n"
    "margin: auto;\n"
    "font-family: sans-serif;\n"
    "}\n"
    "menu a{ color: white; }\n"
    "menu a:visted{ color: white; }\n"
    "menu{\n"
    "padding: 0;\n"
    "width: 100%;\n"
    "background-color: black;\n"
    "}\n"
    "menu ul{\n"
    "padding: 0; margin: 0;\n"
    "padding: 20px 0;\n"
    "list-style: none;\n"
    "}\n"
    "menu li{\n"
    "display: inline-block;\n"
    "width: 25%;\n"
    "text-align: center;\n"
    "}\n"
    "menu li p{\n"
    "line-height: 1;\n"
    "}\n"
    "p {\n"
    "line-height: 1.6;\n"
    "}\n"
    ".sourcecodeSnippet{\n"
    "font-family: Consolas serif;\n"
    "background-color: silver;\n"
    "overflow: auto;"
    "white-space:nowrap;"
    "border: 1px solid black;"
    "}\n"
    ".sourcecodeSnippet .lineNumbers{\n"
    "display:inline-block;\n"
    "text-align: right;"
    "padding: 0 .5em;"
    "border-right: 1px solid black;"
    "}\n"
    ".sourcecodeSnippet .code{\n"
    "display: inline-block;\n"
    "margin-left: 1em;"
    "}\n"
    "code .keyword{\n"
    "color: blue;\n"
    "font-weight: bold;\n"
    "}\n"
    "code .names{\n"
    "color: purple;\n"
    "}\n"
    "code .stringLiteral{\n"
    "color: #46A346;\n"
    "}\n"
